import type { Metadata } from 'next';

import './globals.css';
import { afacad } from './fonts/fonts';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="scroll-smooth">
            <body className={`${afacad.className} antialiased`}>{children}</body>
        </html>
    );
}
